name: Typecheck

on:
  push:
  pull_request:

jobs:
  typecheck:
    # https://youtu.be/yX8yrOAjfKM?t=230
    runs-on: ubuntu-latest
    steps:
      # GitHub checkout clones the repo into the runner
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      # Install pnpm into the runner
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      # Install node on the runner
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          cache: pnpm
      # Install pnpm on the runner and run a TS typecheck
      - run: pnpm install --frozen-lockfile
      - run: pnpm tsc --noEmit
